blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
	
]

blog/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),

   

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    #No necesariamente estos 3 valores (parametors) se deben llamar igual
    path('Nosotros/', views.Nosotros, name = 'nosotros'),

    #LOGIN
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

class Categoria(models.Model):
	nombre = models.CharField(max_length = 60)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):

	titulo = models.CharField(max_length = 150)
	cuerpo = models.TextField()
	imagen = models.ImageField(upload_to = 'noticias')
	categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.titulo

class Comentario(models.Model):
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
	texto = models.TextField(max_length = 1500)
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{noticia}->{texto}"

blog/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
	pass

blog/apps/usuarios/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

blog/apps/noticias/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required

from .models import Noticia, Categoria, Comentario

from django.urls import reverse_lazy

@login_required
def Listar_Noticias(request):
	contexto = {}

	id_categoria = request.GET.get('id',None)

	if id_categoria:
		n = Noticia.objects.filter(categoria_noticia = id_categoria)
	else:
		n = Noticia.objects.all() #RETORNA UNA LISTA DE OBJETOS

	contexto['noticias'] = n

	cat = Categoria.objects.all().order_by('nombre')
	contexto['categorias'] = cat

	return render(request, 'noticias/listar.html', contexto)

@login_required
def Detalle_Noticias(request, pk):
	contexto = {}

	n = Noticia.objects.get(pk = pk) #RETORNA SOLO UN OBEJTO
	contexto['noticia'] = n

	c = Comentario.objects.filter(noticia = n)
	contexto['comentarios'] = c

	return render(request, 'noticias/detalle.html',contexto)


@login_required
def Comentar_Noticia(request):

	com = request.POST.get('comentario',None)
	usu = request.user
	noti = request.POST.get('id_noticia', None)# OBTENGO LA PK
	noticia = Noticia.objects.get(pk = noti) #BUSCO LA NOTICIA CON ESA PK
	coment = Comentario.objects.create(usuario = usu, noticia = noticia, texto = com)

	return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': noti}))

#{'nombre':'nicolas', 'apellido':'Tortosa', 'edad':33}
#EN EL TEMPLATE SE RECIBE UNA VARIABLE SEPARADA POR CADA CLAVE VALOR
# nombre
# apellido
# edad

'''
ORM

CLASE.objects.get(pk = ____)
CLASE.objects.filter(campos = ____)
CLASE.objects.all() ---> SELECT * FROM CLASE

'''

blog/apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegistroForm
# Create your views here.

class Registro(CreateView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('login')
	template_name = 'usuarios/registro.html'

blog/blog/views.py
from django.shortcuts import render

#request 'es un diccionario que continuamente se va pasando entre el navegador y el servidor'

def Home(request):

	return render(request, 't_home.html')


def Nosotros(request):

	return render(request, 't_nosotros.html')

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>MI WEB| {% block titulo %}{% endblock titulo %}</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>


<body class="contenedor">

	<div class="centrar">
		<img src="{% static 'img/logo.png' %}" width="50px" height="50px">
		<a href="{% url 'home' %}">IR AL HOME</a>
		<a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
		<a href="{% url 'noticias:listar' %}">IR A NOTICIAS</a>

		{% if user.is_authenticated %}
			<strong>Hola {{ user.username }}</strong>
			<a href="{% url 'logout' %}">LOGOUT</a>
		{% else %}
			<a href="{% url 'login' %}">LOGIN</a>
			<a href="{% url 'usuarios:registro' %}">Registrar</a>
		{% endif %}
		
		

	</div>

	<div class="bloque">
	{% block contenido %}
	
	{% endblock contenido %}
	</div>
</body>
</html>

blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}


{% block contenido %}
	<h1>ACA VOY A DETALLAR UNA NOTICIA</h1>
		<img src="{{noticia.imagen.url}}" width="500" height="500">
		
		<p>TITULO: {{noticia.titulo}}</p>
		
		<p>FECHA: {{noticia.fecha}}</p>
		<p>CATEGORIA: {{noticia.categoria_noticia}}</p>
		<p>CUERPO: {{noticia.cuerpo}}</p>
		<br><br>
		<br>
		<form method="POST" action="{% url 'noticias:comentar' %}">{% csrf_token %}
			<textarea name="comentario" maxlength="1500"> </textarea>
			<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden=""> 
			<input type="submit" value="GUARDAR">
		</form>
		<br><br><br>
		<h3>COMENTARIOS</h3>
		{% for com in comentarios %}
		{% if user == com.usuario %}
			<a href="">borrar</a>
		{% endif %}
		<strong>FECHA:{{com.fecha}}</strong><br>
		<strong>USUARIO:{{com.usuario}}</strong><br>
		<p>{{com.texto}}</p>
		{% endfor %}
		<a href="{% url 'noticias:listar' %}">VOLVER</a>
{% endblock contenido %}

blog/templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}


{% block contenido %}
	<div class="submenu">

		<a href="{% url 'noticias:listar' %}">TODAS</a>
		{% for cat in categorias %}
			<a href="?id={{cat.pk}}">{{cat.nombre}}</a>
		{% endfor %}

	</div>

	<h1>ACA VOY A LISTAR LAS NOTICIAS</h1>

	{% for noti in noticias %}
		<img src="{{noti.imagen.url}}" width="100" height="100">
		
		<p><a href="{% url 'noticias:detalle' noti.pk %}">TITULO: {{noti.titulo}}</a></p>
		
		<p>FECHA: {{noti.fecha}}</p>
		<p>CATEGORIA: {{noti.categoria_noticia}}</p>
		<p>CUERPO: {{noti.cuerpo}}</p>
		<br><br>
	{% endfor %}
{% endblock contenido %}

blog/templates/t_home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}HOME{% endblock titulo %}


{% block contenido %}
	<h2>HOLA SOY EL HOME</h2>
{% endblock contenido %}

blog/templates/t_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOSOTROS{% endblock titulo %}


{% block contenido %}
	<h2>HOLA SOY NOSOTROS</h2>
{% endblock contenido %}

blog/templates/usuarios/login.html
{% extends 'base.html' %}

{% block contenido %}
			<form method="POST">{%csrf_token%}
				{{form.errors}}
				<input type="text" name="username" placeholder="USUARIO">
				<input type="password" name="password" placeholder="PASSWORD">

				<input type="submit" name="" value="ENVIAR">
			</form>
{% endblock %}

blog/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registro{% endblock %}
{% block contenido %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post">{% csrf_token %}         
         <h3 class="mb-4">Registro</h3>
          {{form.as_p}}
          <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock contenido %}